### ISSUE TITLE
Create a truly portable `jengaboot`.

### ISSUE THREAD

**Issue by jordwalke** [reasonml/rebel#16]
Here's my proposal:

Create a fork of `jenga`, but instead of using `ocaml_plugin`, just compile in `jengaroot` rules statically. Then we can compile all of jenga + our custom rules into a single portable bytecode file that we can check into `npm` and onto `CI` hosts.

(We need to compile in the rules statically instead of using ocaml plugin because ocaml plugin doesn't work when jenga is compiled as byte code).

**Comment by vramana** [comment]
This issue can be closed. cc @chenglou
