### ISSUE TITLE
Bucklescript!

### ISSUE THREAD

**Issue by jaredly** [reasonml/rebel#19]
So it sounds like jengaboot's the future, but I really like bucklescript. What's needed to get this going?

Certainly a way to configure it would be cool (see #18), but to hack things together maybe I'll just try messing with [the jengaroot.re](https://github.com/chenglou/jengaboot/blob/master/node_modules/jengaboot/jengaroot.re#L631) and see what happens?

**Comment by jaredly** [comment]
notes from chat
![image](https://cloud.githubusercontent.com/assets/112170/17616253/6603c25e-6028-11e6-8404-351fda667bd7.png)

**Comment by jordwalke** [comment]
@bobzhang : If BuckleScript adhered to the ocaml compiler CLI exactly, this task would be trivial. We'd just replace `.cmx` with `.cmj` and `ocamlopt` with `bsc`.

**Comment by bobzhang** [comment]
what's jengaboot's convention, where does it install `cm*` files?

**Comment by chenglou** [comment]
Sorry folks, just leaving a note here that I'm busy lately working on (very) related stuff. This is still on my mind.

**Comment by vramana** [comment]
I have one question, how will `rebel` differentiate between js packages and ocaml packages because both them will be combined in `dependencies` field because bucklescript compiler uses different flags for them.  Is looking for `opam` file in the package directory enough to differentiate?

**Comment by vramana** [comment]
This issue can be closed. We now have bucklescript
