### ISSUE TITLE
Properly expose rebel binary.

### ISSUE THREAD

**Issue by jordwalke** [reasonml/rebel#45]
Right now the postinstall script copies the binary location to `../.bin` That won't always work. I suggest doing one of the following:
-  using npm's `bin` feature. (But linking to individual `bin` doesn't work well on windows - instead link to a directory of `bin`s.
- Or adding the following to your `package.json` which allows people whose projects use `dependency-env` to have their run-scripts' `PATH` augmented with the directory containing your binaries:

```
  "exportedEnvVars": {
    "PATH": {
      "global": true,
      "globalCollisionBehavior": "joinPath",
      "resolveAsRelativePath": true,
      "val": "./_build/src/"
    }
  },

```

**Comment by vramana** [comment]
@jordwalke I tried npm's `bin` feature but I couldn't make it work so I went with copying as a temporary solution. Aso I didn't know about dependency-env. Let me submit a PR.

**Comment by jordwalke** [comment]
I like `dependency-env` better because you can set arbitrary PATHs and env variables and we may more feasibly support windows one day

**Comment by jordwalke** [comment]
It does require that users of your binary do the following in their scripts: `eval $(dependencyEnv) && rebel`
