### ISSUE TITLE
ocamlfind dependencies.

### ISSUE THREAD

**Issue by jordwalke** [reasonml/rebel#47]
I'm using the outdated `rebel#bin` package, but maybe it's still an issue. The docs say that `ocamlfindDependencies` should be specified just like your npm dependencies, but I think they need to be specified differently - the key needs to be the ocamlfind package name. For example, even if my package.json specified

```
      "js_of_ocaml-bin": "github:reasonml/js_of_ocaml-bin"
```

My `rebel` config should be:

```
"ocamlfindDependencies": {
      "js_of_ocaml": "github:reasonml/js_of_ocaml-bin"
    }
```

**Comment by vramana** [comment]
Correct. You need to specify the name of the actual package because we pass it to ocamlc. `ocamlfindDependencies` can simply be an array. We don't use the values at all.

Currently we have to manually write ocamlfindDependencies, we should probably automate it using rebel in future.

**Comment by jordwalke** [comment]
an array seems like it would be much easier to understand, especially since it deviates from the `package.json` names.

**Comment by jordwalke** [comment]
Implemented in [this](https://github.com/reasonml/rebel/pull/49) Thanks you!

It's good you support the old version too, since I have older projects using that format.
