### ISSUE TITLE
Benchmark build times 

### ISSUE THREAD

**Issue by vramana** [reasonml/rebel#56]
This can help detecting perf regressions.

**Comment by jordwalke** [comment]
I wish `travis` would allow this somehow. It automatically builds and runs tests on each commit. We merely need it to run some tests and store the output somewhere that we can query (and it needs to try to run the tests on consistently powered machines over time).

**Comment by vramana** [comment]
Hmm. We can store numbers in firebase and have a reason-bot post the current build times vs master as a comment after successful build.

**Comment by jordwalke** [comment]
That's a good idea! Not sure where we'd  store the credentials. We'll consider it a wish list item.

**Comment by jordwalke** [comment]
I bet someone has solved this before. We should find out what other people do.

**Comment by vramana** [comment]
Travis allows Storing environment variables so that shouldn't be a problem.

**Comment by jordwalke** [comment]
But then someone could send a PR that causes those environment variables to be dumped to some third party server (since PRs are automatically ran on travis IIRC).

**Comment by vramana** [comment]
Travis has Secured [Env Variables](https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml) because they only work on reasonml branches and not exposed to PR builds from forks. So this won't work for PRs. But we can use this feature to generate rebel binaries and push it to some storage service.

We just need to write custom server that uses travis [web hooks](https://docs.travis-ci.com/user/notifications/#Webhook-notifications) and extracts numbers from the build log.

**Comment by pbiggar** [comment]
I wouldn't run benchmarks on cloud machines. You're going to get too much noise to see any signal at all.
