### ISSUE TITLE
build with Bucklescript compiler errors

### ISSUE THREAD

**Issue by gnoff** [reasonml/rebel#63]
I tried adding

``` json
  "rebel": {
    "backend": "bucklescript"
  }
```

and

``` json
  "rebel": {
    "backend": "bucklescript",
    "targets": ["Test.re"]
  }
```

to my package.json.

and after clearing _build and running `npm run postinstall` I get the following error

```
*** jenga: [25809] root=/Users/joshstory/projects/RebelExampleProject, sys=Darwin, j=1, f=1 (NO_VERSION_UTIL)
- build . scheme
+ bash -c 'ocamldep -pp refmt -ppx node_modules/bs-platform/bin/bsppx -ml-synonym .re -mli-synonym .rei -modules -one-line -impl src/Test.re 2>&1 ; (exit ${PIPESTATUS[0]})'
sh: node_modules/bs-platform/bin/bsppx: No such file or directory
File "src/Test.re", line 1:
Error: Error while running external preprocessor
Command line: node_modules/bs-platform/bin/bsppx '/var/folders/qh/p_9n0rws5m7b62ntdpc7ymdc0000gn/T/camlppxa93b8e' '/var/folders/qh/p_9n0rws5m7b62ntdpc7ymdc0000gn/T/camlppxe82333'

src/Test.re:
- exit . scheme, 117ms, exited with code 2
*** jenga: 2/4 targets are up to date
*** jenga: failed (#1, 124ms, heap=407.352m, stat=7, digest=0, ls=0, db-save=0)
*** jenga: todo: 0 (2 / 4) !1 ~1 j=0+0 con=4 save=0 act=1, finished
*** jenga: ERROR: (summary) _build/src/index.js: External command failed
      - build . scheme
      + bash -c 'ocamldep -pp refmt -ppx node_modules/bs-platform/bin/bsppx -ml-synonym .re -mli-synonym .rei -modules -one-line -impl src/Test.re 2>&1 ; (exit ${PIPESTATUS[0]})'
      sh: node_modules/bs-platform/bin/bsppx: No such file or directory
      File "src/Test.re", line 1:
      Error: Error while running external preprocessor
      Command line: node_modules/bs-platform/bin/bsppx '/var/folders/qh/p_9n0rws5m7b62ntdpc7ymdc0000gn/T/camlppxa93b8e' '/var/folders/qh/p_9n0rws5m7b62ntdpc7ymdc0000gn/T/camlppxe82333'

      src/Test.re:
      - exit . scheme, 117ms, exited with code 2
*** jenga: build finished; not in polling mode so quitting
*** jenga: Quit; exit_code = 1
```

**Comment by vramana** [comment]
@gnoff You have to use bs-platform 1.0.1 currently. 

Also the targets array should be `targets: [ "Test" ]` You shouldn't add the `.re` extension. 
https://github.com/reasonml/rebel/blob/5cc7ae8e15bc56bb34f696c45b0167d3f7229ada/examples/bs-project/package.json#L13-L17

**Comment by gnoff** [comment]
Thanks @vramana. I have 1.0.3 installed currently. Are you saying that I specifically have to roll back 2 patches to 1.0.1?

**Comment by gnoff** [comment]
Also, i was using opam compiler 4.02.3 and remembered that bucklescript has a variant of this compiler. I switched to 4.02.3+buckle-1 but the result didn't change. In the future is rebel going to be able to switch opam compilers so that they are in sync with what the package wants to build?

**Comment by vramana** [comment]
@gnoff Yes. They made some changes in 1.0.2 which are incompatible with our code. I have sent a patch but it is not released yet. So, we have to wait until 1.1.0. Then we can update code on our side. 

Also We don't use the opam binaries for bucklescript. Currently it points at `node_modules/.bin/bsc`. Also using opam is not the recommended way. 

> In the future is rebel going to be able to switch opam compilers so that they are in sync with what the package wants to build?

No. rebel will be only using packages installed npm and it will use the ocaml compiler that comes with reason or bucklescript compliler that comes from bs-platform. If it's a rebel compatible package, rebel will build it and if it's an OPAM package, it will built in the `postinstall` step of npm and rebel will use it via ocamlfind.

**Comment by gnoff** [comment]
Thanks @vramana. Closing for now. I will attempt with 1.0.1 and open new issues if/when appropriate.
