### ISSUE TITLE
watch or auto build option

### ISSUE THREAD

**Issue by IwanKaramazow** [reasonml/rebel#7]
Should there be something like an auto build option at the level of Jengaboot, or is it up to the user to write a script for this? I'm currently using a simple node script that watches the src folder and rebuilds on change.

**Comment by chenglou** [comment]
Jenga has a watcher, but it's currently linux-only. I guess you could set up your own watcher for now?

**Comment by IwanKaramazow** [comment]
I've set up my own watcher for now, I'll close this issue.

**Comment by jordwalke** [comment]
@IwanKaramazow - What worked well for you?

**Comment by IwanKaramazow** [comment]
@jordwalke : `node watch` + webpack for hmr & js modules in the browser 

``` javascript
// watch.js
const { exec } = require('child_process');
const sane = require('sane'); //wrapper around fs.watch

const src = `${__dirname}/src`;
const compile_command = 'node ./node_modules/.bin/run';

const watcher = sane(src);

watcher.on('change', (filepath, root, stat) => {
    exec(compile_command, (err, stdout, stderr) => {
      if (err) {
        console.error(err);
        return;
      }
      console.log(stdout);
    });
 });
```

It does the job...
