### ISSUE TITLE
Contributor flow - some blocks I ran into

### ISSUE THREAD

**Issue by rickyvetter** [reasonml/rebel#9]
1) I need magic commented incantation to build extractDeps.out.

`ocamlfind ocamlc -pp refmt -linkpkg -package yojson -g -impl extractDeps.re -o extractDeps.out 2>&1 | huh`

2) The built version of berror has some paths hardcoded which causes errors in the build process:
`bash: node_modules/.bin/berror: /Users/chenglou/.opam/4.02.3/bin/ocamlrun: bad interpreter: No such file or directory`

`echo huh > node_modules/.bin/berror` w/ my own copy of better errors installed seems to unblock.

**Comment by chenglou** [comment]
1. See #10.
2. Fixed now through some black magic. Can you try to wipe stuff completely and start a jengaboot from scratch?

**Comment by IwanKaramazow** [comment]
@rickyvetter: if you clone the repo, and you do `cd node_modules/jengaboot && npm run compileUtils`, does this work?

**Comment by chenglou** [comment]
@bsansouci

**Comment by bsansouci** [comment]
I might've have the same problem. My problem was that I had `BetterErrors` inside `node_modules/jengaboot/node_modules` instead of just in `node_modules`. I delete that nested version and ran `npm i BetterErrors`. That fixed it for me.

**Comment by rickyvetter** [comment]
Yeah this works for me. I also had to install realpath to run ./test.sh. But the compileUtils step worked without any issue!

**Comment by IwanKaramazow** [comment]
Ok, then I have a problem in my local filesystem with my npm env 😄

```
git clone https://github.com/chenglou/jengaboot.git && cd jengaboot/node_modules/jengaboot && npm run compileUtils
>> Fatal error: OCaml and preprocessor have incompatible versions
Fatal error: exception Misc.Fatal_error
```

I'll sort this out.

Update, it's definitely related to my env. If I add `eval opam config..` beforehand, it runs fine.

```
eval `opam config env` && ocamlfind ocamlc -pp refmt -linkpkg -package yojson -g -impl buildUtils/extractDeps.re -o buildUtils/extractDeps.out && ocamlfind ocamlc -pp refmt -linkpkg -package yojson -g -impl buildUtils/extractOcamlfindDeps.re -o buildUtils/extractOcamlfindDeps.out`
```

**Comment by chenglou** [comment]
Yeah, most of us have "eval `opam config env`" in our `bashrc`. No idea what it does but once we're completely off opam this wouldn't happen. The entire compiler will be automatically sandboxed inside node_modules.

Fortunately I now reverted to pre-compiling the extract\* binaries so this only affects jengaboot devs. I'll add "eval `opam config env`" to npm `compileUtils` for you great jengaboot devs =].

(@IwanKaramazow hopefully everything else is fixed?)

**Comment by IwanKaramazow** [comment]
Everything runs very smooth, I'm loving the speed. If only I could make those fully functioning typed React bindings working, when npm installing jengaboot... 😉  

I've got the 'eval `opam config env`' in both my `.bashrc` & `.bash_profile`. Mac runs every terminal session as a login session, so `.bash_profile` should dominate (I think). Weird stuff that `npm run` even when added to both, it doesn't get recognized.
